### ISSUE TITLE
Describe the meaning of multiple hit results

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#11]
from @kearwood on the proposal repo:

We should describe why there would be multiple hits, and what order they are returned in. For example, we could say that the XRHitResult's are returned in the order of depth or that they are in order of confidence.

**Comment by lincolnfrog** [comment]
My thinking is that the hits are all intersections with geometry along that ray - e.g. if you are pointing at a table, you would get one intersection for the table and then one for the floor under the table. 

The order should be from closest to the ray origin to furthest from the ray origin. I don't think we can assume there is a "confidence" factor on all underlying systems.

**Comment by blairmacintyre** [comment]
We definitely can't assume confidence since most platforms don't return it.

But, I agree with @lincolnfrog's interpretation.  Some platforms have sparse or incomplete representations of the world (e.g., ARKit/Core's inferred planes).  Those might result in multiple possible hits.

**Comment by lincolnfrog** [comment]
This is now captured in the explainer.
