### ISSUE TITLE
offsetRay--origin is 3D localPosition of ReferenceSpace？

### ISSUE THREAD

**Issue by DLGL99GL** [immersive-web/hit-test#111]
I used Hittest to implement the location marking function in Hololens;
As shown in the picture
I want to change the origin and direction of offsetRay to get the Hittest result pose likes “I need”
but final result likes “I get”,that maked me wonder “the origin is not 3D position offset in viewerpose local system”
why the distance of the two getHitTestResults is getting smaller and smaller;
![image](https://user-images.githubusercontent.com/69023459/179933168-19111d1e-10e9-4807-9ae7-2adf52b85da0.png)

 the origin need transformed the coordinate system by myself? or transformed by system?

![image](https://user-images.githubusercontent.com/69023459/179933422-094d4b6d-5316-427d-80ee-f60a6b5395f7.png)

**Comment by Manishearth** [comment]
This is not the place to get help about using the WebXR API
