### ISSUE TITLE
session.requestHitTestSource not support 'unbounded' and 'bounded-floor'?

### ISSUE THREAD

**Issue by DLGL99GL** [immersive-web/hit-test#112]
```
session.requestReferenceSpace( 'unbounded' ).then( function ( referenceSpace ) {
	session.requestHitTestSource( { space: referenceSpace } ).then( function ( source ) {
		hitTestSource = source;
	} );

} );
```
i tested 'viewer'、‘local’,it worked;but when seted 'unbounded' or 'bounded-floor',  the length of 'frame.getHitTestResults( hitTestSource )' is 0;
Is session.requestHitTestSource not support 'unbounded' and 'bounded-floor'?

**Comment by Manishearth** [comment]
This is not the place to ask for help with the API or about bugs in particular implementations.
