### ISSUE TITLE
createAnchor function missing on XRHitTestResult

### ISSUE THREAD

**Issue by felixtrz** [immersive-web/hit-test#115]
I've noticed that this sample is calling createAnchor() on an XRHitTestResult: https://github.com/immersive-web/webxr-samples/blob/main/hit-test-anchors.html#LL186C26-L186C26

However, this function is missing in the API spec for XRHitTestResult: https://immersive-web.github.io/hit-test/#xr-hit-test-result-interface.

/agenda add createAnchor function to XRHitTestResult API spec

**Comment by AdaRoseCannon** [comment]
It's here: https://immersive-web.github.io/anchors/#anchor-creation

Do you still need this on the agenda for tomorrow?

**Comment by Manishearth** [comment]
Yeah, it's an addition from another spec, it should not be in this spec.

**Comment by felixtrz** [comment]
> It's here: https://immersive-web.github.io/anchors/#anchor-creation
> 
> 
> 
> Do you still need this on the agenda for tomorrow?

I see! I think we don't need to have that on the agenda for tomorrow then!
