### ISSUE TITLE
Support for occlusion

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#13]
@kearwood wrote: "We should describe the behavior of occlusion. Should we include XRHitResult's behind other geometry such as walls detected with the sensors? Should some materials (such as windows or virtual objects) be treated as physically transparent, or perhaps included in the XRHitResult sequence? I would propose that we explicitly identify which entry in the XRHitResult sequence is the nearest physically opaque object."

**Comment by blairmacintyre** [comment]
I would expect:
- hittest to leverage the platform APIs to do hit  testing against whatever representation of the world the platform has.  It will not take virtual elements in the page into account. 
- what this means is up to the UA and how it uses the platform.  A user-agent that runs multiple things at once, and allows one page to see "2D browser windows" of other pages might choose to have those be "pickable" or not.   I don't think the API should define such things.  This should be up to the UA.
- I would hope that the API should define a way to return the hits in order (e.g., closest first) if there are multiple hits.

**Comment by lincolnfrog** [comment]
The hit results are already returned in sorted order (closest first) and we want to, in the future, include the object that was hit. This would let the caller check whether the object is opaque or not if they wanted to allow picking through a window, as per the original example. Closing this in lieu of letting the caller / UA handle this logic and in favor of https://github.com/immersive-web/hit-test/issues/23
