### ISSUE TITLE
Support batching of requests

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#19]
This could be an important feature for several reasons:
- ensuring that related hit-tests get resolved on the same frame
- performance improvement, especially for a synchronous API

**Comment by blairmacintyre** [comment]
Perhaps allow an array of parameters to hitTest in addition to  just one?

**Comment by lincolnfrog** [comment]
This complicates the API surface and there aren't currently any use-cases or performance issues that require such support.
