### ISSUE TITLE
support a synchronous version of the call

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#20]
This would dramatically improve the ergonomics of the API for developers and improve the perceived accuracy / usability of the results
Pros:
- improved calling ergonomics
- more accurate results in some cases, i.e. a reticle wouldn't be perpetually a frame behind

Concerns:
- how do you handle out-of-band requests such as hit-test requests that come from controller events?
- May be slow to jump to native and back to JS - potentially multiple milliseconds (could require batching #19 )
- This could be challenging for all underlying implementations to support
- The majority of the WebXR API is already async

**Comment by blairmacintyre** [comment]
I MUCH prefer to keep it async.  I think that different implementations can implement it differently, and for those that can, I would imagine that they could guarantee that any hitTest before the rAF is resolved before the rAF (so, if you call hit test during your rAF, you will get a result before the next rAF, and any hit tests done in input even handlers will be done before the rAF.)

The limitation is if you want to do a hit test based on a controller ray, and you get that ray ONLY IN the rAF, this would be a problem.  You would have a 1-frame-behind situation.  

The question is:  is this a real problem?  If you are waving a wand around, you might see the 1/90 (or less in future) latency ...

Alternatively, if https://github.com/immersive-web/hit-test/issues/4 let us subscribe to not just a value (screen space value or matrix) but to a ray attached to a controller as well, the problem would be solved.  Each frame, the subscribed "ray" (that is specified relative to a controller) would be hit tested against the world and the data provided

**Comment by jsantell** [comment]
This seems like it wouldn't fly for the concerns you mentioned, as well as it's something that could be added in the future, but difficult to remove. Additionally, user-land could have a library that consumes exposed meshes, planes, feature points, etc. that exposes a synchronous hit test if desired for specific use cases.

**Comment by lincolnfrog** [comment]
Agreed with points above. Closing this issue - there will NOT be a synchronous hit-test.
