### ISSUE TITLE
Clarify promise resolution possibilities

### ISSUE THREAD

**Issue by jsantell** [immersive-web/hit-test#24]
In the current Chrome implementation, upon an unsuccessful hit, `XRSession.prototype.requestHitTest()` either returns a promise resolving to an empty array, or, [due to an issue](https://bugs.chromium.org/p/chromium/issues/detail?id=854823), may reject the promise.

We should clarify in the spec what happens when no hits are found (I assume empty arrays), and what can cause the promise to reject (I imagine if the platform doesn't support hit tests).

**Comment by lincolnfrog** [comment]
https://github.com/immersive-web/hit-test/pull/30
