### ISSUE TITLE
Is raycast returning real-world information only?

### ISSUE THREAD

**Issue by tbalouet** [immersive-web/hit-test#3]
I'm wondering if the raycast system should return real-world information only, or if it should also return information about the virtual world which has been created.
If the hit-test was to return both, how could we differentiate real-world data from the virtual world?

For example, to place an object, the system might want to know if there has been one already placed there, to prevent the user from placing two at the same place, but also check what is the underlying real-world information to place an object underneath (like putting a carpet under a sofa for example).

**Comment by blairmacintyre** [comment]
I think the intention is only to return real-world information:  developers can easily shoot rays through their virtual content if they need.

More importantly:  how would the WebXR implementation know about the application content?

For your object placing example, those decisions sound application specific:  the app can do a hit-test (against the world) and do a hitTest (with the same ray against their own content) and make decisions as appropriate.

**Comment by lincolnfrog** [comment]
Agree with Blair's analysis. Closing this issue.

**Comment by tbalouet** [comment]
Alright, I guess my question was mostly if we'd want to avoid to have 2 raycast for the same origin-direction. In my mind the WebXR implementation could be linked to the scene and thus know the application content, and enable the user to raycast against it through some parameter.
Just trying to raise the potential issues that come to mind ;)

**Comment by lincolnfrog** [comment]
I think trying to make the WebXR system have knowledge of the apps geometry is a huge can of worms and is trying to make it do too much. I think doing two raycasts in this case is appropriate. This does have implications for the usefulness of the hit-test api for VR - I would advocate that it doesn't make sense to return hits in VR.

**Comment by blairmacintyre** [comment]
In future VR systems (e.g., like Windows MR devices, that do inside out tracking), the system may expose more world sensing so that you can know the structure of the room and map things to it.  

One can easily imagine VR systems working in cluttered spaces, but mapping physical props (tables, chairs) to virtual content (i.e., you could sit in the virtual chair, or lean on the virtual table).

I would expect that this will increase over time (i.e., for safety, we could warn users if they are going to bump into something or possibly trip).  So, it's reasonable to assume that VR systems will have more and more world knowledge.

**Comment by thetuvix** [comment]
Agreed that it's likely far more trouble than it's worth to teach WebXR about your middleware's scene graph.  In practice, web developers will be using a single hit-test method provided by their middleware library anyway, which will itself raycast against world understanding as needed under the covers using WebXR's hit-test method.

As @blairmacintyre points out, whether you're in VR or AR, developers will increasingly have both physical and virtual objects to reason about moving forward.  This is a key reason that we're building one web API here across both!

**Comment by lincolnfrog** [comment]
I am going to close this and assume that hit-test won't be used for this kind of world understanding - it seems to make more sense as it's own method related to other world-understanding element retrieval such as getting planes or meshes.
