### ISSUE TITLE
Hit-test capability detection api ?

### ISSUE THREAD

**Issue by sarathsi** [immersive-web/hit-test#36]
Is there hit-test capability detection API available/any plans to add? For eg., supportsHittest() before using requestHitTest() on XRSession.

**Comment by lincolnfrog** [comment]
This is part of session creation and is covered by the XRModes discussion here: https://github.com/immersive-web/webxr/issues/394

It is likely that hit-test must be part of basic AR support and thus will be available in any session that is allowed to resolve as an AR-type session.

**Comment by jsantell** [comment]
In demos and codelabs, we've been using `XRSession.prototype.requestHitTest`'s existence as a hint of AR support, although it could exist on platforms that implement WebXR and not have AR capabilities (for example enabling WebXR+hit tests on Chrome on desktop)
