### ISSUE TITLE
requestHitTest error callback without reason

### ISSUE THREAD

**Issue by ranbuch** [immersive-web/hit-test#37]
I'm trying to use the requestHitTest with a Galaxy S9 and Chrome Canary (71.0.3562.0)

I've enabled all of the necessary chrome://flags like written [here](https://codelabs.developers.google.com/codelabs/ar-with-webxr/#1) and [this demo](https://web-education-ar-demo.appspot.com/) works great on my device.

When calling ```session.requestHitTest``` with ```await``` I'm not getting to the next line of code and I'm getting ```Uncaught (in promise) undefined``` on console.

I've tried to get the error like that:

```javascript
this.session.requestHitTest(origin,
            direction,
            frameOfRef).then(
                (data) => {console.log(data)},
                (err) => {console.log(err)}
            );
```

but ```err``` is ```undefined```.

```requestHitTest``` parameters are:
```javascript
origin = Float32Array(3) [0, 0, 0]
direction = Float32Array(3) [-0.0012410288909450173, 0.009024959988892078, -0.9999585151672363]
frameOfRef = XRFrameOfReference {emulatedHeight: 0, bounds: null}
```

Any idea on what am I doing wrong?
Can you provide an error for the fallback?

Thank you.

**Comment by jsantell** [comment]
I've ran into this where the Chrome devtools show an uncaught error on a slightly different line, like right after the hit test. I suspect it's something to do with errors not halting execution (the next frame is still called) and some sort of devtools confusion. A try/catch block around the hit test request should work, as some rejections are to be expected if a hit can not be performed for any reason.

That being said, the lack of an error is confusing and the above is a Chrome issue, and I think it'd be worthwhile to have an expected error type or message for these failures codified in the spec.

**Comment by jsantell** [comment]
As per #30, the error should be detailed as a string:

> If the promise rejects, there was an error (should be detailed in a returned string). It could be that the API is unsupported by the platform or the XRSession is not of the right type for AR. It could be an internal error of some kind.

I don't know how I feel about strings (seems less likely to standardize or reasonably pattern match), but could be a defined Error type with some enum maybe for the type of rejection, but that seems challenging to abstract over a spec for all devices to anticipate reasons their AR platform would reject, and because of that I am still of the camp that rejecting a hit test because of an implementation failure is a leaky abstraction and as a dev, I do not care if ARCore just found no planes, or was unable to cast a ray because it was out of its current field of view.

**Comment by ranbuch** [comment]
I think ```requestHitTest``` should just return 0 hits in case of such an expected failure.
After all, most of the times he's not able to return nothing.

Probably be best if the API whould resolve an Object with hits and more data instead of rejecting.

**Comment by ddorwin** [comment]
Note that per the TAG's promises guide, ["Rejections Should Be Used for Exceptional Situations."](https://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional) There are some useful examples of when and when not to reject.

**Comment by lincolnfrog** [comment]
We have determined that this is a bug in Chrome's implementation due to the usage of ARCore 1.1's 2D hit-test API instead of the now-supported 3D API. If you move the device quickly enough, the ray that is generated can not be converted into a valid 2D point on the device's screen.

This will be resolved soon when we upgrade our API.

**Comment by ranbuch** [comment]
On [model-viewer web component example](https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html) I can see that the hit test is much more reliable now but on my code it still returns a lot of errors (both running on my Android device on Chrome Canary 72.0.3616.0).

When comparing ```model-viewer``` source code to mine I cannot recognize any different that may cause this issue.

Is it some difference that I've missed or are they running on ```origin trials```?

What are the reasons for a frequent errors on ```requestHitTest```, I rarely get a valid response.

**Comment by daserge** [comment]
For me [setting `renderer.shadowMap.enabled` to `true`](https://codelabs.developers.google.com/codelabs/ar-with-webxr/#6) causes this error for some reason.

**Comment by lincolnfrog** [comment]
The main reason we are getting these errors, as I mentioned above, is because of errors in projecting between 2D and 3D. Support for the 3D API is already in ARCore and we are working on making Chrome use that.

I HIGHLY doubt renderer.shadowMap.enabled could affect this - that seems like a red herring.

**Comment by jsantell** [comment]
> On [model-viewer web component example](https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html) I can see that the hit test is much more reliable now but on my code it still returns a lot of errors (both running on my Android device on Chrome Canary 72.0.3616.0).
> 
> When comparing `model-viewer` source code to mine I cannot recognize any different that may cause this issue.
> 
> Is it some difference that I've missed or are they running on `origin trials`?
> 
> What are the reasons for a frequent errors on `requestHitTest`, I rarely get a valid response.

model-viewer does not have any privileged code or origin trials enabled

> For me [setting `renderer.shadowMap.enabled` to `true`](https://codelabs.developers.google.com/codelabs/ar-with-webxr/#6) causes this error for some reason.

shadows use framebuffers different than the default one in three.js. Here's a commit [removing a hacky workaround and replaces with three's renderer.setFramebuffer](https://github.com/googlecodelabs/ar-with-webxr/commit/457726ababa964811dd41485faaedb60eecf37a4)

**Comment by bialpio** [comment]
Closing - if you still have any issues in Chrome, please file a bug in Chrome-specific bug tracker (https://crbug.com).

**Comment by ranbuch** [comment]
@bialpio I know that's not the best place to ask but in Chrome 79 the `Device API` flag is on by default. What about the `Hit Test`?
Can I place a model on `local-floor` without it?
The [web-xr](https://immersive-web.github.io/webxr-samples/xr-barebones.html) example opens a `VR Mode`.
When will this [ar-hit-test](https://immersive-web.github.io/webxr-samples/proposals/phone-ar-hit-test.html) be working? Can I enable it via `origin trials`?

**Comment by bialpio** [comment]
Hit test flag still needs to be enabled manually for the proposed hit test APIs to work. In addition, there's also a #webxr-ar-module flag that also needs to be enabled for AR features to work. You should be able use `local-floor` for model placement (you'd have to compute the ray-floor intersection point in JavaScript), but right now Chrome's implementation of `local-floor` space is based on a hard-coded estimate so it might seem a bit off. I think the AR examples in immersive-web/webxr-samples repository were not updated in a while - the hit test example that should be working in Chrome Canary can be found [here](https://storage.googleapis.com/chromium-webxr-test/latest.html?target=proposals/phone-ar-hit-test.html).
