### ISSUE TITLE
interaction between hit testing and an "AR lite" mode

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/hit-test#38]
Over in the webxr repo there was a discussion of how to create an AR lite mode (https://github.com/immersive-web/webxr/issues/402) that got moved to the proposals repo (https://github.com/immersive-web/proposals/issues/29).

I just posted a comment on how we can defer strong decisions on that, if we adopt the attitude that the hit test functionality might fail for reasons other than "the platform doesn't have enough world knowledge about where you tried to hit test" (which is, implicitly, the way hit test works right now).

Specifically, if we make it clear that the UA might restrict hit testing for other reasons (e.g., user choice), we can enable different browsers to experiment with different approaches to privacy, without requiring a more explicit "AR lite" mode (yet).

Thoughts?

**Comment by bialpio** [comment]
Closing stale issue. I feel that it's not an issue specific to hit test API - the UA will just compute hit test based on the level of information agreed to by the user.
