### ISSUE TITLE
Support reticle functionality (continuous hit-test subscription?)

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#4]
Since having a reticle in the world is a common use-case, it would be nice to have an API for creating a subscription to a particular ray or screen-space coordinate and get results every frame (possibly as part of the frame data?).

To support a controller reticle, which could be moving, maybe it needs a callback to get the current ray?

**Comment by blairmacintyre** [comment]
This seems like a convenience function that could be implemented pretty easily in javascript, right?

The question I would have here is, are we comfortable guaranteeing the platform can provide this information each frame without latency.  

The implication of adding it to the frame is "this is the result of the hit-test at the location for this frame data".  Perhaps it could be supplied, perhaps it might not be able to be.

I could imagine that it would be more efficient to subscribe on some platforms, where the browser implementation could do the intersection with the world "at the right time".  

But, it might also be the case that if it can be done each frame, it would then be able to be done from JS each frame.  Unclear to me.

**Comment by lincolnfrog** [comment]
This interacts with the timing considerations discussed in https://github.com/immersive-web/hit-test/issues/10 - if there is no guarantee about how many frames may elapse in between asking for a hit-test and getting the result, then would the reticle stutter instead of flow smoothly?

I agree we should probably leave this to JS for the time-being. Hopefully the performance of these hit-test calls are good enough that we will generally get the results back before the next frame...

**Comment by lincolnfrog** [comment]
In our community call, this was called out as a potential issue with the current spec. We might want to consider providing the "reticle location" each frame along with the frame data to support a pixel-perfect reticle given how ubiquitous the use-case is.

**Comment by blairmacintyre** [comment]
On reflection, I do agree that being able to indicate you want a hit test to be a one-shot, or continuous, does seem useful.  But, yes, it would require something other than a promise;  perhaps having the data in the frame data passed to rAF, or firing an event instead of resolving a promise

**Comment by lincolnfrog** [comment]
This is covered by the relative-ray functionality described in https://github.com/immersive-web/hit-test/pull/31
