### ISSUE TITLE
Clarify which frame `requestAsyncHitTestResult()` should return results for

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/hit-test#43]
The first real-world hit testing features were added in PR immersive-web/webxr#493, including an `requestAsyncHitTestResult()` function.  The initial design has this function exposed off of an `XRFrame` with the intention that the hit-test results will be relative to the frame on which they were requested.
In the PR comments and the Jan '19 F2F, there were concerns raised that this wasn't possible to implement on some platforms and, furthermore, would be out of accordance with the developer intention.
There are a number of variations to the API shape which are possible, but before we propose anything concrete, we need to get a deeper understanding of the desired behavior and platform limitations.

**Comment by bialpio** [comment]
Closing for now - promise-based API is out of scope for now.
