### ISSUE TITLE
Update hit-testing-explainer.md to match the current core WebXR spec

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/hit-test#47]
This explainer was originally written against an earlier version of the WebXR spec. There references to two attributes that no longer exists in WebXR. There may be other such references as well.

1. `XRReferenceSpace.originOffset` - the surrounding text can probably be simplified since the offset cannot be changed.
1. `XRSession.viewerSpace`

**Comment by bialpio** [comment]
Explainer should be up-to-date now.
