### ISSUE TITLE
How should XRRay.matrix be initialized for XRRay(transform)?

### ISSUE THREAD

**Issue by takahirox** [immersive-web/hit-test#79]
In [`XRRay` section](https://immersive-web.github.io/hit-test/#xrray-interface), it isn't mentioned how `XRRay.matrix` should be initialized for `XRRay(transform)` while it's mentioned for `XRRay(origin, direction)` "Initialize ray’s matrix to null".

How should it be initialized for `XRRay(transform)`? Copy `transform.matrix`? Or set `null` and lazily generate as `XRRay(origin, direction)` does?

**Comment by Manishearth** [comment]
null as well, it's just null for lazy loading

**Comment by takahirox** [comment]
Thanks. I'll make a PR to add it.
