### ISSUE TITLE
Ray parameter as full matrix?

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#8]
To be consistent with the rest of WebXR, the ray should be specified as a full 4x4 matrix rather than a position/direction vector pair. This is technically over-specified for a ray and shearing a ray is not something that would be useful, however the argument could be made that it is more compatible with the math types that are acquired from other systems so you can just feed parameters in directly without having to generate a origin/direction.

**Comment by blairmacintyre** [comment]
I think on the last call I was advocating for the point/vector, but I don't feel strongly either way.  The argument that many libraries use matrices is compelling;  three.js uses Ray's for it's intersection's, tho.  So, it's unclear if that's a strong argument.

It's a ray.  Represent it as a ray!

**Comment by blairmacintyre** [comment]
Aside from the issue of needing multiple sorts of hitTests (screen-based and ray-based) (e.g., #7), I'd tend to agree.

**Comment by lincolnfrog** [comment]
Closing as WebXR is now using XRRays directly so using a ray here is more consistent with the spec.
