### ISSUE TITLE
Question - What scenarios exist that require Hit Test as a separate module compared to facilitated through real world geometry APIs?

### ISSUE THREAD

**Issue by chrisfromwork** [immersive-web/hit-test#95]
I'll be the first to admit that I am somewhat naive to the history of this hit-test module design. I may be missing some fundamental scenarios that require hit-testing.

But, is there a reason why hit testing is offered as a separate module to real world geometry? It seems like hit testing is limited to real world geometries compared to dealing with engine scene content. It feels like it may prove more intuitive to perform a ray cast against scene content + real world geometries at the engine layer compared to relying on webxr to generate a real world geometry.

Right now it seems like you would need to perform two hit testing operations to get the correct ray cast position in the engine scene (one for the real world geometry and then a second for the engine scene content). Would it be better if an engine handled all ray casting against both scene and real world geometries?

**Comment by blairmacintyre** [comment]
All scenarios where you don't want to expose room geometry to the web page.  Unlike native apps, WebXR has the opportunity (and, following web privacy goals, duty) to limit exposure of information to web pages.  

So, any app where you just want to place an item on a surface (shopping, etc).
Any app where you want to put content in the room (e.g., "show me the 3D object floating in front of me") and don't need the geometry.
And, any app where you (the user) aren't sure you trust the website (many apps could fall into this, even if the app experience is degraded).

**Comment by chrisfromwork** [comment]
Thanks @blairmacintyre !
